sudo: required
services:
  - docker
#dewvelpoment file to test the application first
before_install:
  - docker build -t ori/flask-test -f ./advanced_python/Dockerfile . #build context
#runnning the test 
script:
- docker run -e CI=true ori/flask-test python app.py run -h 192.168.1.233

after_success:
  - docker build -t orirothschild/flask-prod -f ./advanced_python/Dockerfile.prod #build context
  - docker build -t orirothschild/flask-nginx ./advanced_python/nginx #builld context
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push orirothschild/flask-prod
  - docker push orirothschild/flask-nginx

# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-west-1-201546747467
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET 