version: '3.7'

services:
  app:
    build: ./flask-app
    command: python app.py run -h 0.0.0.0
    volumes:
      - ./flask-app:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=hello_flask
    - POSTGRES_PASSWORD=hello_flask
    - POSTGRES_DB=hello_flask_dev
  nginx:
    depends_on:
      - app
    restart: always
    build:
      context: ./nginx
    ports:
      #dont let anny node modules inside the folder to overrite the one inside a container
      - '3050:80'
volumes:
    postgres_data: